### PR TITLE
Various fixes and improvements

### LINKED ISSUE #230: /orgs/admin/ds returns wrong or duplicate information
```
{
  "id": 12,
  "slug": "5ad1ayhjvpsflksv",
  "name": "5ad1ayhjvpsflksv",
  "creationDate": "2021-12-29T10:49:09.9710471",
  "objectsCount": 0,
  "lastEdit": null,
  "properties": {
    "entries": 2,
    "meta": {
      "name": {
        "data": "Brighton Beach",
        "id": "6a5c7db7-e00c-431d-b7a8-86e0d862ad2c",
        "mtime": 1640797543
      }
    },
    "public": true
  },
  "isPublic": true,
  "size": 7956545
}
```

 * objectsCount is wrong and redundant (entries)
 * lastEdit is wrong (and not needed)
 * isPublic is redundant
 * name is redundant (superseded by meta)

### PR DESCRIPTION
**Pull request by HeDo88TH**
This PR will close #230 #231 #227 #212 plus numerous other improvements and fixes!

### CODE REVIEW

**Comment by HeDo88TH** [comment]
https://github.com/DroneDB/Registry/pull/236/commits/342cfe284b33e9e0e32f829b14ecda955fc92c99 closes #230

**Comment by HeDo88TH** [comment]
Build docker image (in Registry folder)

```
docker build -t dronedb/registry .
```

Run registry stand alone (sqlite + integrated users + in memory storage/cache). 

```
cp appsettings-default.json appsettings.json
docker run -it -p 5000:5000 -v ${PWD}/App_Data:/Registry/App_Data -v ${PWD}/appsettings.json:/Registry/appsettings.json dronedb/registry
```

I will add these info to the readme and on the website 👍

**Comment by HeDo88TH** [comment]
Regarding #227, I see no point in adding a startup script (like webodm) because dotnet has the simple command: `dotnet run --project Registry.Web`

#212 cannot be solved, I tried on Windows to watch for writes in the temp folder but I could not find any. On build, the only write on temp folder is the uploaded file then everything happens inside the ddb folder.

Here it is the new `Serilog` configuration (replaces the old `Logging` section)

```
"Serilog": {
    "LevelSwitches": {
      "$controlSwitch": "Information"
    },
    "MinimumLevel": {
      "ControlledBy": "$controlSwitch"
    },
    "Using": [
      "Serilog.Sinks.Console",
      "Serilog.Sinks.File"
    ],
    "WriteTo": [
      {
        "Name": "Console"
      },
      {
        "Name": "File",
        "Args": {
          "path": "logs/registry.txt"
        }
      }
    ],
    "Enrich": [
      "FromLogContext",
      "WithMachineName",
      "WithThreadId"
    ],
    "Destructure": [
      {
        "Name": "ToMaximumDepth",
        "Args": {
          "maximumDestructuringDepth": 4
        }
      },
      {
        "Name": "ToMaximumStringLength",
        "Args": {
          "maximumStringLength": 100
        }
      },
      {
        "Name": "ToMaximumCollectionCount",
        "Args": {
          "maximumCollectionCount": 10
        }
      }
    ],
    "Properties": {
      "Application": "Registry"
    }
  },
```

To reduce the log size use `"Warning"` in place of `"Information"`

**Comment by pierotofy** [comment]
I think we should provide a startup script (for both Windows and Linux), imo.

It should be as simple as:

`./registry.sh start`

Or double-clicking a `.bat` file.

**Review by pierotofy — APPROVED** [review]

**Comment by pierotofy** [comment]
Good improvements!

**Pull request merged**
