### PR TITLE
Add zip download

### LINKED ISSUE #76: Add /orgs/:org/ds/:ds/download endpoint
`GET /orgs/:org/ds/:ds/download`

Takes an optional `path` query parameter `?p=file1.JPG,..` of comma-separated paths to limit the download scope (e.g. `?p=DJI_0018.JPG,DJI_0019.JPG` returns a zip file with only two files). This can include directories (but no wildcards).

If a single file is selected via `path`, the download should return the file directly, without zipping.
If two or more files are selected, the files should be returned in zip format.

The endpoint should NOT zip the files on disk and return them after the zip is completed! This can delay the download time significantly because the system would spend a lot of time compressing the archive and then returning it. The zip file should be streamed over to the request (e.g. write the compressed file directly to the network stream) without touching the file system.

`POST /orgs/:org/ds/:ds/download`

Similar to the`GET` endpoint, but takes one or more `path` body form-data parameters to  limit the download scope (necessary because URLs can only be 2000 characters long, so we might run into issues).

Returns a single object:

```
{
   "downloadUrl" : <url>
}
```

Which is a temporary GET url and can be used by the user to download the results.

In case of error the answer for both endpoints is:

```
{ 
   "error": "description"
}
```

With status of 400.

See MiniReg's implementation for reference.

### PR DESCRIPTION
**Pull request by HeDo88TH**
Adds the zip feature and Closes #76

### CODE REVIEW

**Comment by HeDo88TH** [comment]
New endpoints:

Download single file or archive of files
`GET orgs/{orgSlug]/ds/{dsSlug}/download?p=path1,path2,...,pathN`

Create download link for file or archive of files
`GET orgs/{orgSlug]/ds/{dsSlug}/download`
`paths`: array of strings (in form-data simply repeat the same key)
`expiration`: expiration of the package (if not present the package is a one-time download)
`isPublic`: if the generated download link is a public link (no auth required)

**Review by pierotofy — COMMENTED** [review]
`path` (not `p`) is optional. (My bad, I think I wrote `p` in the issue. MiniReg uses `path`).

Currently returns:

```
{
    "error": "No paths provided"
}
```

The POST endpoint takes multiple `path` form data arguments. Not a single `paths`.

image

Compare the implementation with that of MiniReg (there's a reason I'm writing these things in MiniReg, that way the specs are clear and there's no misunderstandings). https://github.com/DroneDB/MiniReg

**Comment by HeDo88TH** [comment]
Now It's ok 👍

**Comment by pierotofy** [comment]
Nice, thanks!

**Pull request merged**
