### PR TITLE
Added file upload limits

### LINKED ISSUE #33: Verify and improve behaviour of endpoints when uploading large files
We are using MemoryStreams to manipulate in-memory the uploaded file content. This could lead to performance issues when dealing with large files. We should check IF this is the case and what we can do to mitigate it.

### PR DESCRIPTION
**Pull request by HeDo88TH**
Fixes #33 , you can now set the max file upload size

### CODE REVIEW

**Comment by HeDo88TH** [comment]
Closes #31

**Comment by pierotofy** [comment]
But this affects all repos (both private and public)?

To be clear, it should be possible to upload a very large file if the user is logged-in.

**Comment by pierotofy** [comment]
Does this work if I set MaxRequestBodySize to 30GB and upload a 20GB file?

**Comment by pierotofy** [comment]
Didn't realize this branch wasn't separate from #54 -.-

Comments above still apply.

**Pull request merged**
