### PR TITLE
Improved docker file

### PR DESCRIPTION
**Pull request by HeDo88TH**
Config should be adjusted, it's kinda working now

### CODE REVIEW

**Comment by pierotofy** [comment]
We can merge this, but you might find that you want to keep the normal compilation process for building the .NET bindings.

We won't be able to use the convenience install script for installing the bindings.

Up to you to merge or not.

**Comment by HeDo88TH** [comment]
It is not necessary to build the bindings because they are linked as a nuget package. They will be downloaded prebuilt from the nuget repository. What registry needs is having ddb in its path, and that's the aim of the convenience script, isnt it?
Now i'm working on the migration from calling the executable to calling the ddb bindings, we are going to remove some settings from the config.

**Comment by pierotofy** [comment]
Yes, but... ddb is installed with exodus.

If you can find a way to get dotnet to pick up the `libddb.so` path (and its dependencies), go for it. I haven't been able to do it, because `dotnet` is very opinionated as to where library files are installed, and any path other than standard `usr/lib`, `/usr/local/lib` is going to give you trouble.

I suspect you will run into troubles. But if you find a way to make it work... sure!

**Comment by pierotofy** [comment]
Friendly reminder to not merge your own PRs into master! :warning: 

This dockerfile is not going to work on Linux.

**Comment by HeDo88TH** [comment]
I'm working on ddb to update the bindings and then I will test it. I merged because I added other developments that were tested successfully. The dockerfile is not used yet, it can be broken.

**Comment by pierotofy** [comment]
I was using the dockerfile...

**Comment by pierotofy** [comment]
Edit: just realized that I wrote this:

> Up to you to merge or not.

So it was OK to merge. :pray: my fault, apologies.

**Comment by HeDo88TH** [comment]
Don't worry, It's my bad because I didn't put 8349b48, d677cf1, ba51218 and 8b61557 in a separate branch but I commited to master. I forgot I had this MR open and the latest changes were "safe" to be committed on master :grin:

**Pull request merged**
