### PR TITLE
Switch to .NET DDB bindings

### LINKED ISSUE #37: Use .NET bindings instead of system calls to ddb exe
We should use the .NET bindings library instead of invoking the ddb executable.

### PR DESCRIPTION
**Pull request by HeDo88TH**
The aim of this PR is to perform a total switch from calling ddb executable to using .NET DDB bindings. Possibly via the Nuget package..

Closes #37

### CODE REVIEW

**Comment by pierotofy** [comment]
(Is this ready for review?)

Getting:

```
{
    "error": "Cannot initialize ddb in folder './ddbstore\\admin\\abc1'"
}
```

When calling `/share/upload`

**Comment by HeDo88TH** [comment]
> (Is this ready for review?)
> 
> Getting:
> 
> ```
> {
>     "error": "Cannot initialize ddb in folder './ddbstore\\admin\\abc1'"
> }
> ```
> 
> When calling `/share/upload`

Nono, It's totally a draft!

**Comment by HeDo88TH** [comment]
There is something wrong with sqlite and its sqlite mod_spatialite

```
   System.InvalidOperationException : Cannot initialize ddb in folder './Data/Ddb\test\first'
  ----> DDB.Bindings.DDBException : no such function: InitSpatialMetaData
```
I'm investigating this issue because it's what's preventing us from mergin this PR

**Comment by pierotofy** [comment]
Are you initializing the bindings?

**Comment by HeDo88TH** [comment]
> Are you initializing the bindings?

Yes, It was a path problem :scream:

**Comment by HeDo88TH** [comment]
I think we are good now @pierotofy

**Comment by pierotofy** [comment]
Looks good! Nice work :+1:

**Pull request merged**
