### PR TITLE
Support optional tag

### LINKED ISSUE #52: Support for optional tag
Expand the logic of `/share/init` to cover the following scenario:

1. User is logged-in (provides a valid authentication token)
2. Does not provide a `tag` field.

Registry should:

1. Pick `<username>` as the organization name (by the same logic, we should make sure that an organization name equal to the username should always exist).
2. Pick a random dataset slug.

### PR DESCRIPTION
**Pull request by HeDo88TH**
Fixes #52

### CODE REVIEW

**Comment by pierotofy** [comment]
Getting a:

```
{
    "error": "Unexpected end when deserializing array. Path '', line 1, position 1."
}
```

When calling `POST /share/upload` with a single file (JPG) with path `test/abc/test18.jpg` (a nominal test case).

```
      Executed DbCommand (2ms) [Parameters=[@__path_0='test/abc/test18.jpg' (Size = 19)], CommandType='Text', CommandTimeout='30']
      SELECT "e"."path", "e"."depth", "e"."hash", "e"."meta", "e"."mtime", "e"."point_geom", "e"."polygon_geom", "e"."size", "e"."type"
      FROM "entries" AS "e"
      WHERE "e"."path" = @__path_0
      LIMIT 1
fail: Registry.Web.Controllers.ShareController[0]
      Exception in Share controller Upload('gRqBlSIsIgrmYvDPW2n0Gcgsgtvh87Yl', 'test/abc/test18.jpg', 'DJI_0018.JPG')
Newtonsoft.Json.JsonSerializationException: Unexpected end when deserializing array. Path '', line 1, position 1.
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ThrowUnexpectedEndException(JsonReader reader, JsonContract contract, Object currentObject, String message)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value)
   at Registry.Adapters.DroneDB.Ddb.Info(String path) in D:\RegistryApp\Registry.Adapters.DroneDB\Ddb.cs:line 34
   at Registry.Adapters.DroneDB.DdbStorage.Add(String path, Byte[] data) in D:\RegistryApp\Registry.Adapters.DroneDB\DdbStorage.cs:line 88
   at Registry.Web.Services.Adapters.ObjectsManager.AddNew(String orgSlug, String dsSlug, String path, Byte[] data) in D:\RegistryApp\Registry.Web\Services\Adapters\ObjectsManager.cs:line 162
   at Registry.Web.Services.Adapters.ObjectsManager.AddNew(String orgSlug, String dsSlug, String path, Byte[] data) in D:\RegistryApp\Registry.Web\Services\Adapters\ObjectsManager.cs:line 177
   at Registry.Web.Services.Adapters.ShareManager.Upload(String token, String path, Byte[] data) in D:\RegistryApp\Registry.Web\Services\Adapters\ShareManager.cs:line 305
   at Registry.Web.Controllers.ShareController.Upload(String token, String path, IFormFile file) in D:\RegistryApp\Registry.Web\Controllers\ShareController.cs:line 62
   at Registry.Web.Controllers.ShareController.Upload(String token, String path, IFormFile file) in D:\RegistryApp\Registry.Web\Controllers\ShareController.cs:line 64
```

**Review by pierotofy — CHANGES_REQUESTED** [review]
Has regression that needs to be fixed.

**Comment by HeDo88TH** [comment]
I've tested it with ddb v0.9.3 and it works. That serialization error originates from the `ddb info` command that didn't return anything (empty string). It happens when ddb crashes. 
There is indeed a regression that is the return object of `share/init`:

```
{
    "token": "eZI2OpF9te8be3aTP22rJUxlazej16nU",
    "tag": "admin/mgmzvbvvzfhyo6zx"
}
```

Since `tag ` can be auto-generated it is now required to return it to the client.

**Comment by pierotofy** [comment]
Huh, must have been a problem with ddb. Using https://github.com/DroneDB/DroneDB/releases/download/v0.9.3/ddb-0.9.3-windows.zip worked.

I don't understand the need for returning the `tag`. The client doesn't need it. Why return it? Can we remove it?

**Comment by HeDo88TH** [comment]
> Huh, must have been a problem with ddb. Using https://github.com/DroneDB/DroneDB/releases/download/v0.9.3/ddb-0.9.3-windows.zip worked. 👍
> 
> Can the .NET bindings be added next? I think it will avoid issues like this one more easily.
> 
> I don't understand the need for returning the `tag`. The client doesn't need it. Why return it? Can we remove it?

The client needs it because it is auto-generated by the registry and the client doesn't know where his files have been put.

**Comment by pierotofy** [comment]
The client, currently, does not care about a tag.

All it cares about is where files are uploaded to (URL).

We need to agree on some design choices here:
 - Keep it simple
 - Don't add fields / features / parameters unless there's a clear, proven need for them

Can we do that?

**Comment by HeDo88TH** [comment]
> The client, currently, does not care about a tag.
> 
> All it cares about is where files are uploaded to (URL).
> 
> We need to agree on some design choices here:
> 
> * Keep it simple
> * Don't add fields / features / parameters unless there's a clear, proven need for them
> 
> Can we do that?

I do agree to those design choices. 
It is needed because if the client wants to check (for any reason) the status of the upload process He needs to call dataset batches endpoint. That endpoints needs the slug of the dataset, which is auto-generated by the registry.
He can extract the Tag from the Url parameter of CommitResultDto but he has no way of knowing it before calling commit.
I think that it's important to add that parameter to the share init endpoint in order to give more flexibility to the client. 
Remember that the registry API can also be consumed by other clients beyond ddb.

**Comment by pierotofy** [comment]
Clients that currently do not exist. We're making assumptions.

**Comment by HeDo88TH** [comment]
> Clients that currently do not exist. You're making assumptions.
> 
> Comment it out if you think this will be needed in the future and you don't want to delete it.

I think it's useful now and will be more useful in the future. 
It stays, I will PR dronedb to handle it accordingly.

**Comment by HeDo88TH** [comment]
Moved the `tag` field from `share init` to `share commit`

**Comment by pierotofy** [comment]
:+1:

**Pull request merged**
