### PR TITLE
Fix file limit size

### LINKED ISSUE #99: Cannot upload large files
`test1` is a 2GB file (empty).

The command:

```
ddb share test1 -s https://testhub.dronedb.app
```

After a while, registry responds with:

```
Error response from registry: Cannot add 'test1' to ddb './ddbstore/pierotofy/8205b2d8-6d76-4a9b-bd66-655353ece07e'
```

### PR DESCRIPTION
**Pull request by HeDo88TH**
Closes #99

### CODE REVIEW

**Comment by HeDo88TH** [comment]
It's not published yet, I'm still working on DB migrations

**Comment by HeDo88TH** [comment]
It is now live on testhub

**Comment by pierotofy** [comment]
Is this ready for review?

**Comment by HeDo88TH** [comment]
It would be in draft if not ready for review 👍

**Pull request merged**
