### PR TITLE
Add meta endpoints

### PR DESCRIPTION
**Pull request by HeDo88TH**
Closes https://github.com/DroneDB/Registry/issues/178

CI will fail until https://github.com/DroneDB/DDB.Bindings/pull/17 is merged and new nuget package is published.

### New Meta API

**REST Compliant**

```
GET ​/orgs​/{orgSlug}​/ds​/{dsSlug}​/meta​/list
GET ​/orgs​/{orgSlug}​/ds​/{dsSlug}​/meta​/get​/{key}
POST ​/orgs​/{orgSlug}​/ds​/{dsSlug}​/meta​/add​/{key}
POST ​/orgs​/{orgSlug}​/ds​/{dsSlug}​/meta​/set​/{key}
DELETE ​/orgs​/{orgSlug}​/ds​/{dsSlug}​/meta​/remove​/{id}
DELETE ​/orgs​/{orgSlug}​/ds​/{dsSlug}​/meta​/unset​/{key}
```

**NON REST Compliant** 

`key`, `path` and `data` are `formdata` parameters (`path` and `key` can also be provided via query string)

```
GET ​/orgs​/{orgSlug}​/ds​/{dsSlug}​/meta​/list
GET ​/orgs​/{orgSlug}​/ds​/{dsSlug}​/meta​/get​/{key}
POST ​/orgs​/{orgSlug}​/ds​/{dsSlug}​/meta​/add
POST ​/orgs​/{orgSlug}​/ds​/{dsSlug}​/meta​/set
POST ​/orgs​/{orgSlug}​/ds​/{dsSlug}​/meta​/remove
POST ​/orgs​/{orgSlug}​/ds​/{dsSlug}​/meta​/unset
```

Check `/swagger` for further details about parameters.

### CODE REVIEW

**Comment by pierotofy** [comment]
```curl --location --request POST '192.168.2.253:5000/orgs/admin/ds/test/meta/add/annotations' \
--header 'Authorization: Bearer token \
--form 'data="123"'
```

Returns:

```
{
    "type": "https://tools.ietf.org/html/rfc7231#section-6.5.13",
    "title": "Unsupported Media Type",
    "status": 415,
    "traceId": "00-103753645ba7984cbe6bc4d1dd259313-68229eb1fb479d41-00"
}
```

**Comment by pierotofy** [comment]
```
curl --location --request POST '192.168.2.253:5000/orgs/admin/ds/test/meta/add?key=annotations' \
--header 'Authorization: Bearer <token>' \
--form 'data="123"'
``

Returns:

```
{
    "error": "Key should not be null or empty"
}
```

Is this PR ready or did I misinterpreted the request for review?

**Comment by HeDo88TH** [comment]
> ```
> curl --location --request POST '192.168.2.253:5000/orgs/admin/ds/test/meta/add/annotations' \
> --header 'Authorization: Bearer <token> \
> --form 'data="123"'
> ```
> 
> Returns:
> 
> ```
> {
>     "type": "https://tools.ietf.org/html/rfc7231#section-6.5.13",
>     "title": "Unsupported Media Type",
>     "status": 415,
>     "traceId": "00-103753645ba7984cbe6bc4d1dd259313-68229eb1fb479d41-00"
> }
> ```

It is correct, if you use the REST endpoint you can not use formdata. Use the other endpoint instead.

> ```
> curl --location --request POST '192.168.2.253:5000/orgs/admin/ds/test/meta/add?key=annotations' \
> --header 'Authorization: Bearer <token>' \
> --form 'data="123"'
> ```
> 
> Returns:
> 
> ```
> {
>     "error": "Key should not be null or empty"
> }
> ```
> 

It is correct too, because, as I wrote before, the only querystring parameter supported is `path`

> Is this PR ready or did I misinterpreted the request for review?

You did not read my post and did not check /swagger before testing 👍

**Comment by pierotofy** [comment]
> It is correct, if you use the REST endpoint you can not use formdata.

Umm, how do I use the REST endpoint then? Can you post an example?

**Comment by pierotofy** [comment]
Even the defaults in swagger don't work:

```
curl -X 'POST' \
  'http://192.168.2.253:5000/orgs/admin/ds/test/meta/add/annotations' \
  -H 'accept: */*' \
  -H 'Content-Type: application/json-patch+json' \
  -d '"string"'
```
```
{
  "error": "Object serialized to String. JObject instance expected."
}
```

**Comment by pierotofy** [comment]
Non-REST endpoints don't work either:

```
curl -X 'POST' \
  'http://192.168.2.253:5000/orgs/admin/ds/test/meta/add' \
  -H 'accept: */*' \
  -H 'Content-Type: multipart/form-data' \
  -F 'key=annotations' \
  -F 'data=123' \
  -F 'path='
```

```
{
  "error": "Object serialized to Integer. JObject instance expected."
}
```

**Comment by pierotofy** [comment]
To simplify this whole PR; just keep the NON-REST endpoints (Stripe style), having this redundancy just makes the software more complicated and adds unnecessary things to test. :pray:

**Comment by pierotofy** [comment]
Another problem: the API seems to ignore permissions/authentication. I can list the meta as an anonymous user for a dataset set as private.

**Comment by pierotofy** [comment]
This error happens because the endpoints expects a JSON object.

```
{
  "error": "Object serialized to Integer. JObject instance expected."
}
```

Meta can be: a JSON object, a JSON array or any Javascript scalar value (a JToken).

Perhaps keeping the bindings with Data of type JToken would have prevented this?

**Comment by HeDo88TH** [comment]
> Another problem: the API seems to ignore permissions/authentication. I can list the meta as an anonymous user for a dataset set as private.

This was fixed in https://github.com/DroneDB/Registry/pull/181/commits/9f71f7f98979488bdc6208e1d1ee653a7a28c1ac, there was a global policy that made the Public attribute on the organization to override the Private one on the dataset.

> This error happens because the endpoints expects a JSON object.
> 
> ```
> {
>   "error": "Object serialized to Integer. JObject instance expected."
> }
> ```
> 
> Again, `data` can be: a JSON object, a JSON array or any Javascript scalar value (a JToken).
> 
> Perhaps keeping the bindings with Data of type JToken would have prevented this.

Actually it was a typo https://github.com/DroneDB/Registry/pull/181/commits/0d77cfabe5baebbc5077beac566b7e158627ca3e

These are my tests:

```
curl -X 'POST' \
  'https://localhost:5001/orgs/hedo88/ds/test/meta/add?key=annotations' \
  -H 'accept: */*' \
  -H 'Content-Type: multipart/form-data' \
  -F 'data=this is a string'
  
curl -X 'POST' \
  'https://localhost:5001/orgs/hedo88/ds/test/meta/add?key=annotations' \
  -H 'accept: */*' \
  -H 'Content-Type: multipart/form-data' \
  -F 'data=12345'
  
curl -X 'POST' \
  'https://localhost:5001/orgs/hedo88/ds/test/meta/add?key=annotations' \
  -H 'accept: */*' \
  -H 'Content-Type: multipart/form-data' \
  -F 'data=[1234, "this is a string", {"test": 1234}]'
  
curl -X 'POST' \
  'https://localhost:5001/orgs/hedo88/ds/test/meta/set?key=config' \
  -H 'accept: */*' \
  -H 'Content-Type: multipart/form-data' \
  -F 'data={"settings": ["ciao","a","tutti"]}'
  
curl -X 'POST' \
  'https://localhost:5001/orgs/hedo88/ds/test/meta/set?key=config' \
  -H 'accept: */*' \
  -H 'Content-Type: multipart/form-data' \
  -F 'data=321'
  
curl -X 'GET' \
  'https://localhost:5001/orgs/hedo88/ds/test/meta/list' \
  -H 'accept: */*'
  
curl -X 'GET' \
  'https://localhost:5001/orgs/hedo88/ds/test/meta/get/annotations' \
  -H 'accept: */*'

[
  {
    "data": "this is a string",
    "id": "1ac774aa-1511-45b5-8e62-46970c3a0601",
    "mtime": 1631961050
  },
  {
    "data": 12345,
    "id": "b662decd-ad3b-4abb-a4e2-b2a29c8fafe1",
    "mtime": 1631961069
  },
  {
    "data": [
      1234,
      "this is a string",
      {
        "test": 1234
      }
    ],
    "id": "52a0793b-4a25-4fc9-8c03-6400324abe10",
    "mtime": 1631961100
  }
]
  
  
curl -X 'GET' \
  'https://localhost:5001/orgs/hedo88/ds/test/meta/get/config' \
  -H 'accept: */*'

curl -X 'POST' \
  'https://localhost:5001/orgs/hedo88/ds/test/meta/remove' \
  -H 'accept: */*' \
  -H 'Content-Type: multipart/form-data' \
  -F 'id=b662decd-ad3b-4abb-a4e2-b2a29c8fafe1'
  
curl -X 'POST' \
  'https://localhost:5001/orgs/hedo88/ds/test/meta/unset?key=annotations' \
  -H 'accept: */*' \
  -H 'Content-Type: multipart/form-data'
```

**Comment by HeDo88TH** [comment]
There is an issue with the implementation of `MetaManager::entryPath` https://github.com/DroneDB/DroneDB/blob/172368a89e74585302978ed11856eb08f9702b14/src/metamanager.cpp#L10
This is preventing Registry from using the `path` parameter because we are calling ddb from a different folder. This is the error that pops out:

This file exists on my test dataset: `https://localhost:5001/orgs/hedo88/ds/test/download/20200830_160445.jpg`
But if I call

```
curl -X 'POST' \
  'https://localhost:5001/orgs/hedo88/ds/test/meta/add/annotations?path=20200830_160445.jpg' \
  -H 'accept: */*' \
  -H 'Content-Type: application/json-patch+json' \
  -d '"string"'
```

This is what ddb says:

```
{
  "error": "Error in calling ddb lib. Last error: \"Path ../../../20200830_160445.jpg not available in index\", check inner exception for details"
}
```

I debugged it until `entryPath` call and I found out that it transforms the path to relative to ddb folder. How can we circumvent this?

**Comment by pierotofy** [comment]
Try with https://github.com/DroneDB/DroneDB/pull/282

**Comment by HeDo88TH** [comment]
> Try with [DroneDB/DroneDB#282](https://github.com/DroneDB/DroneDB/pull/282)

Now it works!

> Another problem: the API seems to ignore permissions/authentication. I can list the meta as an anonymous user for a dataset set as private.

I found an issue on Hub interface that shows "private" when the dataset is actually "public". It peforms the call to chattr correctly but does not show it. I checked the curl call and it works on public datasets but it does not on private ones.

**Comment by HeDo88TH** [comment]
@pierotofy It's working as intended now!

**Comment by pierotofy** [comment]
Private/public bug in Hub is fixed via https://github.com/DroneDB/Hub/commit/f5efa31b206e6bc676160da745d746aca3623581

**Pull request merged**
