### PR TITLE
Remove s3 support

### PR DESCRIPTION
**Pull request by HeDo88TH**
Extensive overhaul and refactor to remove S3 support: speed and horizontal scaling are top priorities.

### CODE REVIEW

**Comment by pierotofy** [comment]
Is this done?

**Comment by HeDo88TH** [comment]
> Is this done?

This should be extensively tested, I'll write down what we should test soon.

**Comment by pierotofy** [comment]
`BridgeCacheExpiration` in `appsettings-default.json` is probably obsolete now?

**Comment by pierotofy** [comment]
Registry (or ddb?) seems to keep input TIFFs open forever anytime  you upload one.

1. Upload a GeoTIFF
2. Open "resmon" and search for the GeoTIFF's filename.

image

The handle is never released, so one cannot move the file.

**Comment by pierotofy** [comment]
Deleting the file causes it to be removed from the index, but not from the filesystem.

**Comment by HeDo88TH** [comment]
> Registry (or ddb?) seems to keep input TIFFs open forever anytime you upload one.
> 
> 1. Upload a GeoTIFF
> 2. Open "resmon" and search for the GeoTIFF's filename.
> 
> image
> 
> The handle is never released, so one cannot move the file.

I doubt that Registry holds onto it. it's more probable that ddb thumbnail / tiler is not releasing the file handle. I will investigate into this.

**Comment by pierotofy** [comment]
Should be fixed with https://github.com/DroneDB/DroneDB/pull/300

**Comment by pierotofy** [comment]
`FileCache`, `FileCacheManagers` can be removed?

**Comment by pierotofy** [comment]
> Deleting orthophotos while being tiled results in an IOException (File already in use)

I think this was caused by DroneDB/DroneDB#300

**Comment by pierotofy** [comment]
I think we can go ahead and merge/deploy this.

**Pull request merged**
